basePath: /api
definitions:
  api.responseApiError:
    properties:
      msg:
        example: error message
        type: string
    type: object
  api.responseLocalStateQueryCurrentEra:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
  api.responseLocalStateQueryEraHistory:
    type: object
  api.responseLocalStateQueryGenesisConfig:
    type: object
  api.responseLocalStateQueryProtocolParams:
    type: object
  api.responseLocalStateQuerySystemStart:
    properties:
      day:
        type: integer
      picoseconds:
        type: integer
      year:
        type: integer
    type: object
  api.responseLocalStateQueryTip:
    properties:
      block_no:
        type: integer
      epoch_no:
        type: integer
      era:
        type: string
      hash:
        type: string
      slot_no:
        type: integer
    type: object
  api.responseLocalTxMonitorHasTx:
    properties:
      has_tx:
        type: boolean
    type: object
  api.responseLocalTxMonitorSizes:
    properties:
      capacity:
        type: integer
      size:
        type: integer
      tx_count:
        type: integer
    type: object
  api.responseLocalTxMonitorTxs:
    properties:
      tx_bytes:
        example: <base64 encoded transaction bytes>
        format: base64
        type: string
      tx_hash:
        example: 96649a8b827a5a4d508cd4e98cd88832482f7b884d507a49466d1fb8c4b14978
        format: base16
        type: string
    type: object
host: localhost
info:
  contact:
    email: support@blinklabs.io
    name: Blink Labs
    url: https://blinklabs.io
  description: Cardano Node API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: cardano-node-api
  version: "1.0"
paths:
  /chainsync/sync:
    get:
      parameters:
      - description: whether to start from the current tip
        in: query
        name: tip
        type: boolean
      - description: slot to start sync at, should match hash
        in: query
        name: slot
        type: integer
      - description: block hash to start sync at, should match slot
        in: query
        name: hash
        type: string
      responses:
        "101":
          description: Switching Protocols
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.responseApiError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.responseApiError'
      summary: Start a chain-sync using a websocket for events
      tags:
      - chainsync
  /localstatequery/current-era:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.responseLocalStateQueryCurrentEra'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.responseApiError'
      summary: Query Current Era
      tags:
      - localstatequery
  /localstatequery/era-history:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.responseLocalStateQueryEraHistory'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.responseApiError'
      summary: Query Era History
      tags:
      - localstatequery
  /localstatequery/genesis-config:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.responseLocalStateQueryGenesisConfig'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.responseApiError'
      summary: Query Genesis Config
      tags:
      - localstatequery
  /localstatequery/protocol-params:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.responseLocalStateQueryProtocolParams'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.responseApiError'
      summary: Query Current Protocol Parameters
      tags:
      - localstatequery
  /localstatequery/system-start:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.responseLocalStateQuerySystemStart'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.responseApiError'
      summary: Query System Start
      tags:
      - localstatequery
  /localstatequery/tip:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.responseLocalStateQueryTip'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.responseApiError'
      summary: Query Chain Tip
      tags:
      - localstatequery
  /localtxmonitor/has_tx/{tx_hash}:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.responseLocalTxMonitorHasTx'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.responseApiError'
      summary: Check if a particular TX exists in the mempool
      tags:
      - localtxmonitor
  /localtxmonitor/sizes:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.responseLocalTxMonitorSizes'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.responseApiError'
      summary: Get mempool capacity, size, and TX count
      tags:
      - localtxmonitor
  /localtxmonitor/txs:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/api.responseLocalTxMonitorTxs'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.responseApiError'
      summary: List all transactions in the mempool
      tags:
      - localtxmonitor
  /localtxsubmission/tx:
    post:
      description: Submit an already serialized transaction to the network.
      parameters:
      - description: Content type
        enum:
        - application/cbor
        in: header
        name: Content-Type
        required: true
        type: string
      produces:
      - application/json
      responses:
        "202":
          description: Ok
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "415":
          description: Unsupported Media Type
          schema:
            type: string
        "500":
          description: Server Error
          schema:
            type: string
      summary: Submit Tx
schemes:
- http
swagger: "2.0"
